
/**
 * @description enter事件
 * @param hc 
 */

export const handleEnter = (hc) => {
  document.onkeydown = (e) => {
    var event = window.event || e || arguments.callee.caller.arguments[0];
    console.log( event.target.parentNode.className )
    if (event.keyCode && event.keyCode == 13&& event.target.parentNode.className != "el-input el-pagination__editor is-in-pagination") {
      hc();
    } else if (event.which == 13&& event.target.parentNode.className != "el-input el-pagination__editor is-in-pagination") {
      hc()
    }
  }
}
const errorList = [
  {status:"1",value:"TCM授权失败"},
  {status:"2",value:"索引错误"},
  {status:"3",value:"参数错误"},
  {status:"4",value:"审计操作失败"},
  {status:"5",value:"标识位被设置"},
  {status:"6",value:"TCM处于无效模式"},
  {status:"7",value:"TCM处于禁用模式"},
  {status:"8",value:"目标命令被禁用"},
  {status:"9",value:"操作失效"},
  {status:"10",value:"不认识的命令序列"},
  {status:"11",value:"安装所有权的能力被禁用"},
  {status:"12",value:"密钥句柄不能被解读"},

  {status:"13",value:"密钥句柄指向无效密钥"},
  {status:"14",value:"不能接受的加密策略"},
  {status:"15",value:"迁移授权失败"},
  {status:"16",value:"PCR信息不能被解读"},
  {status:"17",value:"没有足够的空间"},
  {status:"18",value:"没有安装SMK"},
  {status:"19",value:"加密数据块无效"},
  {status:"20",value:"所有者已经存在"},
  {status:"21",value:"TCM没有足够的内部资源执行请求操作"},
  {status:"22",value:"随机字符串太短"},

  {status:"23",value:"TCM没有足够的空间执行该操作"},
  {status:"24",value:"使用的PCR与TCM当前的PCR不匹配"},
  {status:"25",value:"命令的paramSize参数值错误"},
  {status:"26",value:"没有SM3线程"},
  {status:"27",value:"SM3线程出现错误"},
  {status:"28",value:"自检失败，TCM关闭"},
  {status:"29",value:"命令第二个密钥授权失败"},
  {status:"30",value:"命令Tag参数错误"},
  {status:"31",value:"传输信息给TCM时发生I/O错误"},
  {status:"32",value:"加密过程出现问题"},

  {status:"33",value:"解密过程未完成"},
  {status:"34",value:"使用无效句柄"},
  {status:"35",value:"TCM没有安装EK"},
  {status:"36",value:"不被允许的Key用法"},
  {status:"37",value:"不被允许的实体类型"},
  {status:"38",value:"TCM_Init命令后发送了错误的命令序列"},
  {status:"39",value:"签名数据不能包含DER信息"},
  {status:"40",value:"TCM_KEY_PARM结构不支持该密钥特性"},
  {status:"41",value:"密钥迁移策略错误"},
  {status:"42",value:"密钥的签名或者加密策略错误"},
  {status:"43",value:"密钥相关数据大小不一致或不匹配"},
  {status:"44",value:"参数模式不正确"},
  {status:"45",value:"physicalPresence或physicalPresenceLock位存在错误的值"},
  {status:"46",value:"TCM不能执行给定版本的能力"},

  {status:"47",value:"TCM不允许掩护传输会话"},
  {status:"48",value:"审计操作失败后，后续命令进入返回错误"},
  {status:"49",value:"审计操作成功，后续命令返回成功"},
  {status:"50",value:"尝试重置不具备重置功能的PCR寄存器"},
  {status:"51",value:"尝试重置不在当前Locality下可重置的PCR寄存器"},
  {status:"52",value:"错误的类型标识"},
  {status:"53",value:"预备保留的上下文与当前实际环境不一致"},

  {status:"56",value:"使用非当前被操作NV许可的授权操作"},
  {status:"57",value:"操作需要签名的命令"},
  {status:"60",value:"NV被锁，不能执行写操作"},
  {status:"61",value:"当前Locality不能执行该操作"},
  {status:"62",value:"NV只能读"},
  {status:"63",value:"当前NV不能被写"},
  {status:"65",value:"NV写操作已完成，不能执行写操作"},
  {status:"66",value:"Nv区域属性冲突"},
  {status:"67",value:"结构的tag和version域无效或不匹配"},
  {status:"69",value:"计数器句柄错误"},
  {status:"70",value:"写操作未完成"},

  {status:"71",value:"被保存的上下文间隙太大"},
  {status:"72",value:"超过没有所有者时最大的NV写限制"},
  {status:"73",value:"没有设置操作者授权数据"},
  {status:"74",value:"上下文指定的资源未被加载"},

  {status:"78",value:"有命令在排外传输会话外执行"},
  {status:"88",value:"错误的句柄"},
  {status:"90",value:"无效的上下文"},
  {status:"91",value:"需保存的上下文超过TCM允许数量"},
  {status:"92",value:"迁移授权验证失败"},
  {status:"93",value:"迁移目标未被授权"},
  {status:"94",value:"被迁移数据不正确"},
  {status:"95",value:"不正确的授权迁移"},
  {status:"97",value:"尝试撤销不可撤销EK"},
  {status:"98",value:"错误的签名"},
  {status:"99",value:"上下文列表中没有足够的空间"},
  {status:"102",value:"不支持的算法"},

  {status:"128",value:"度量失败"},
  {status:"129",value:"命令对应的头部信息错误"},
  {status:"130",value:"内存不足"},
  {status:"131",value:"数据加载失败"},
  {status:"132",value:"flash在进行串行化数据失败"},
  {status:"133",value:"TPCM无法处理该命令"},
  {status:"134",value:"参数不合法"},
  {status:"135",value:"传入参数对应的实际大小不同"},
  {status:"136",value:"数据结构中没有对应的项"},
  {status:"137",value:"TPCM日志错误"},
  {status:"138",value:"存储的内容超过了规定的最大限制"},
  {status:"139",value:"搜索不到key"},
  {status:"140",value:"读取的数据不存在"},
  {status:"141",value:"系统版本低于原版本"},
  {status:"142",value:"内存映射失败"},
  {status:"143",value:"验签失败"},
  {status:"144",value:"已经执行的命令"},
  {status:"145",value:"所需空间超过最大容量"},
  {status:"146",value:"无效的license"},
  {status:"147",value:"失效的license"},
  {status:"148",value:"Flash写失败"},
  {status:"149",value:"Flash读取失败"},
  {status:"150",value:"Flash 擦除过程失败"},
  {status:"151",value:"TPCM不支持的特性"},
  {status:"152",value:"重复数据"},
  {status:"153",value:"签名失败"},
  {status:"154",value:"SM3计算失败"},
  {status:"155",value:"数据恢复失败"},
  {status:"156",value:"License重置失败"},
  {status:"157",value:"license类型错误"},
  {status:"158",value:"系统时间设置错误"},
  {status:"159",value:"配置参数类型不对"},
  {status:"160",value:"没有认证证书"},
  {status:"161",value:"认证失败"},
  {status:"162",value:"没有二级证书"},
  {status:"163",value:"策略认证目标或者认证参数为空"},
  {status:"164",value:"认证类型错误"},
  {status:"165",value:"设置全局策略认证失败"},
  {status:"166",value:"口令认证失败"},
  {status:"167",value:"SM4加密失败"},
  {status:"168",value:"指定的PCR类性/PCR索引错误"},
  {status:"169",value:"认证UID为空"},
  {status:"170",value:"证书不匹配"},
  {status:"171",value:"认证标识不可信"},
  {status:"172",value:"策略认证hash不匹配"},
  {status:"173",value:"非法动作操作"},
  {status:"174",value:"随机数生成失败"},
  {status:"175",value:"SM2加密失败"},
  {status:"176",value:"认证策路flag项错误"},
  {status:"177",value:"SM2验签失败"},
  {status:"178",value:"TPCM与TCM通信失败"},
  {status:"179",value:"TPCM获取TCM信息失败"},
  {status:"180",value:""},
  {status:"181",value:"策略数错误"},
  {status:"182",value:"管理认证策略输入参数策略id冲突"},
  {status:"183",value:"Tpcm id 验证失败"},
  {status:"184",value:"策略目标错误"},
  {status:"185",value:"策略认证类型"},

  {status:"256",value:"不支持的命令类型"},
  {status:"257",value:"无效命令号"},
  {status:"258",value:"映射失败"},
  {status:"259",value:"命令队列空间已满"},
  {status:"260",value:"无效参数"},

  {status:"512",value:"命令接收超时"},
  {status:"513",value:"命令类别不支持"},
  {status:"514",value:"没有内存"},
  {status:"515",value:"命令发送失败"},
  {status:"516",value:"缓冲区空间不足"},

  {status:"1024",value:"非法参数"},
  {status:"1025",value:"内存不足"},
  {status:"1026",value:"数据传输出错"},
  {status:"1027",value:"传入参数超过TSS可接收上限"},
  {status:"1028",value:"传出数据超过传出参数可接收上限"},
  {status:"1029",value:"未找到对应表项"},
  {status:"1030",value:"非法的response数据流"},
  {status:"1031",value:"非法的response TAG标识"},
  {status:"1032",value:"打开设备文件失败"},
  {status:"1033",value:"映射失败"},
  {status:"1034",value:"创建或者打开文件失败"},
  {status:"1035",value:"读文件失败"},
  {status:"1036",value:"写文件失败"},
  {status:"1037",value:"重复创建"},
  {status:"1038",value:"执行shell失败"},
  {status:"1039",value:"不支持的操作"},
  {status:"1040",value:"创建随机数失败"},
  {status:"1041",value:"目录操作失败"},
  {status:"1042",value:"验证失败"},
  {status:"1043",value:"Nonce不匹配"},
  {status:"1044",value:"不可信的系统环境"},
  {status:"1045",value:"TSB授权检查错误"},
  {status:"1046",value:"调用TSB接口返回错误"},

  {status:"2048",value:"TCM太忙不能立即响应"},
  {status:"2049",value:"TCM_ContinueSelfTest没有运行"},
  {status:"2050",value:"当前命令执行需要的资源未被测试"},
  {status:"2051",value:"TCM处于字典攻击锁定延时期"},

  {status:"4096",value:"非法参数"},
  {status:"4097",value:"非法路径"},
  {status:"4098",value:"文件操作失败"},
  {status:"4099",value:"内存不足"},
  {status:"4100",value:"返回参数非法"},
  {status:"4101",value:"获取当前系统时间出错"},
  {status:"4102",value:"超时"},
  {status:"4103",value:"未找到对应表项"},
  {status:"4104",value:"传入参数超过TSS可接收上限"},
  {status:"4105",value:"传出数据超过传出参数可接收上限"},
  {status:"4106",value:"创建随机数失败"},
  {status:"4107",value:"调用TSB接口返回错误"},
  {status:"4108",value:""},
  {status:"4109",value:"信号量获取失败"},
  {status:"4110",value:"监听失败"},
  {status:"4111",value:"版本号错误"},

  {status:"2147487745",value:"HMAC校验失败"},
  {status:"2147487746",value:"空指针"},
  {status:"2147487747",value:"无效参数"},
  {status:"2147487748",value:"openssl接口调用失败"},
  {status:"2147487749",value:"输入输出错误"},
  {status:"2147487750",value:"内存错误"},
  {status:"2147487751",value:"文件操作失败"},
  {status:"2147487752",value:"无效数据"},
  {status:"2147487753",value:"命令流数据过大"},
  {status:"2147487754",value:"缓冲区空间不足"},
  {status:"2147487755",value:"无效结构"},

  {status:"2147487756",value:"找不到表项"},
  {status:"2147487757",value:"环境变量未设置"},
  {status:"2147487759",value:"响应数据流TAG无效"},

  {status:"2147487760",value:"无效的签名"},
  {status:"2147487762",value:"校验值出错"},

  {status:"2147487763",value:"无效的响应数据流"},
  {status:"2147487764",value:"无效的会话类型"},
  {status:"2147487765",value:"关闭文件失败"},
  {status:"2147487766",value:"写文件失败"},
  {status:"2147487767",value:"读文件失败"},
  {status:"2147487768",value:"打开驱动设备文件失败"},

  {status:"-254",value:"退出程序信号"},
  {status:"-253",value:"重新加载信号"},
  {status:"-252",value:"业务繁忙"},
  {status:"-251",value:"一般错误"},

  {status:"-250",value:"命令不支持"},
  {status:"-249",value:"模块未加载"},
  {status:"-248",value:"已注册"},
  {status:"-247",value:"TCF接口调用错误"},
  {status:"-246",value:"sqlite数据库错误"},
  {status:"-245",value:"NV区域写错误"},
  {status:"-244",value:"NV区域读错误"},
  {status:"-243",value:"文件路径不存在"},
  {status:"-242",value:"文件大小错误"},
  {status:"-241",value:"内存错误"},

  {status:"-240",value:"数据包数据错误"},
  {status:"-239",value:"连接/接受超时"},
  {status:"-238",value:"连接失败"},
  {status:"-237",value:"数据包格式错误"},
  {status:"-236",value:"配置错误"},
  {status:"-235",value:"初始化失败"},
  {status:"-234",value:"资源不足"},
  {status:"-233",value:"注册失败"},
  {status:"-232",value:"状态不匹配"},
  {status:"-231",value:"下载失败"},

  {status:"-1",value:"终端策略响应超时"},

  {status:"-11",value:"报文节点内存错误"},
  {status:"-12",value:"传输信息给服务发生错误"},
  {status:"-21",value:"数据库打开失败"},
  {status:"-22",value:"数据库更新数据失败"},
  {status:"-23",value:"数据库插入数据失败"},
  {status:"-24",value:"数据库删除数据失败"},
  {status:"-25",value:"数据库查询数据失败"},
  {status:"-32",value:"网络路径转换错误"},
  {status:"-35",value:"验签数据长度不正确"},
]

export function errorValue (param) {
  var errorVal=""
  errorList.map(function(item,index) {
    if(item.status == param) {
      errorVal = item.value
    }
  })
  return errorVal
}